<a href="https://colab.research.google.com/github/RiazullJannat/Python_For_Ai_Ml/blob/main/Numpy_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1, 2,3])
arr=arr*5
print(arr)

[ 5 10 15]


In [ ]:
arr1 = np.array([2, 3, 4])

In [ ]:
arr2 = np.array([
    [1, 2,3],
    [4, 5, 6]
])

In [ ]:
arr3 = np.array([
    [[1,2,3],[4, 5,6]],
    [[1,2,3],[4, 5,6]],
])


In [ ]:
#dimentation
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

#data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

#size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
int64
int64
int64
(3,)
(2, 3)
(2, 2, 3)
3
6
12


In [ ]:
arr = np.array([1, 2, 3,"44"])
print(arr.dtype)

<U21


In [ ]:
arr = np.array([1, 2, 300])
print(arr.dtype)
arr = arr.astype(np.int8)
print(arr.dtype)
print(arr)

int64
int8
[ 1  2 44]


In [ ]:
s = {1, 2, 3}
arr = np.array(list(s))
print(arr)
print(arr.dtype)

[1 2 3]
int64


In [ ]:
dc = {"a":1, "b":2}
arr = np.array(list(dc.items()))
print(arr)
print(arr.dtype)
print(arr.ndim)
print(arr.size)
print(arr.shape)

[['a' '1']
 ['b' '2']]
<U21
2
4
(2, 2)


In [ ]:
#generate array with random value
arr = np.random.rand(2,3)
print(arr)


[[0.67977685 0.9546654  0.66894261]
 [0.44646571 0.49002396 0.74422002]]


In [ ]:
arr= np.random.randint(4,10,(2,2))
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[[6 9]
 [7 4]]
int64
(2, 2)
4
2


In [ ]:
# random value with uniform
arr = np.random.uniform(1,10,(3,2,2))
print(arr)

[[[4.3655364  8.11343259]
  [2.32693371 5.06647204]]

 [[6.11884025 6.62734246]
  [3.71190776 1.27980388]]

 [[1.18659216 3.32836499]
  [8.19457058 4.00414234]]]


In [ ]:
# array using range functions
arr = np.arange(1,10, 1).reshape(3,3)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64
(3, 3)
9
2


In [ ]:
# np.linespace(star, end, how much points we want)
arr = np.linspace(1, 10, 5)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[ 1.    3.25  5.5   7.75 10.  ]
float64
(5,)
5
1


In [ ]:
# np.logspace(start,end, how much points we want)
arr = np.logspace(0, 4, 5,base=2)
print(arr)
print(arr.dtype)

[ 1.  2.  4.  8. 16.]
float64


Indexing and slicing
