<a href="https://colab.research.google.com/github/RiazullJannat/Python_For_Ai_Ml/blob/main/Numpy_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import numpy as np

arr = np.random.randint(1, 100,(10, 5))
# arr.reshape(5,10)
print(arr)
flatten = arr.flatten()
print(flatten)

column_wise_flatten = np.ravel(arr, order="F")
print(column_wise_flatten)

[[65 50 17 66 30]
 [24  5 18  5 20]
 [15 67  6 11  1]
 [68 26 61 48 95]
 [39 76 50 11 58]
 [22 61 23 60 60]
 [17 67  3 28 86]
 [30 30 37 72 76]
 [98 19 95 35  3]
 [70 74 37 82 18]]
[65 50 17 66 30 24  5 18  5 20 15 67  6 11  1 68 26 61 48 95 39 76 50 11
 58 22 61 23 60 60 17 67  3 28 86 30 30 37 72 76 98 19 95 35  3 70 74 37
 82 18]
[65 24 15 68 39 22 17 30 98 70 50  5 67 26 76 61 67 30 19 74 17 18  6 61
 50 23  3 37 95 37 66  5 11 48 11 60 28 72 35 82 30 20  1 95 58 60 86 76
  3 18]


In [44]:
a = np.random.randint(1, 10,(2,3))
b = np.random.randint(10,20,(2,3))



In [45]:
#concatenate
conRow = np.concatenate((a,b), axis=0)

print(conRow)
print("-------X------")
conCol = np.concatenate((a,b),axis=1)
print(conCol)

[[ 3  8  9]
 [ 4  2  3]
 [12 10 10]
 [17 17 12]]
-------X------
[[ 3  8  9 12 10 10]
 [ 4  2  3 17 17 12]]


In [46]:
#erros

x=np.random.randint(1, 10,(2,3))
y=np.random.randint(10,20,(1,3))


In [47]:
c = np.concatenate((x,y),axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

**Transpose**


In [48]:
mat = np.array([
    [10,20,30],
    [30,40,50]
])
transpost = mat.T
print(transpost)

[[10 30]
 [20 40]
 [30 50]]


In [49]:
#array split
a = np.random.randint(1,10,(10,))
splitted_array = np.array_split(a,3)
print(splitted_array)

print(np.split(a,3))

[array([6, 4, 6, 3]), array([8, 2, 5]), array([5, 8, 3])]


ValueError: array split does not result in an equal division

**Arithmetic operator and mathematical functions**

In [55]:

x = np.array([10, 8, 16, 40])
y = np.array([2, 3, 4, 5])

add = x+y
print(add)
sub = x-y
print(sub)
mul = x*y
print(mul)
div = x/y
print(div)


[12 11 20 45]
[ 8  5 12 35]
[ 20  24  64 200]
[5.         2.66666667 4.         8.        ]


In [52]:
sin_val =np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

#radent to degree
deg_con = np.rad2deg(x)
print(deg_con)

[-0.54402111  0.98935825 -0.98803162  0.74511316]
[-0.83907153 -0.14550003  0.15425145 -0.66693806]
[ 572.95779513  458.3662361  1718.87338539 2291.83118052]


In [56]:
#log
log_val_10 = np.log10(x)
print(log_val_10)
log_val_2 = np.log2(x)
print(log_val_2)


#squire root
squire_root = np.sqrt(x)
print(squire_root)
#

[1.         0.90308999 1.20411998 1.60205999]
[3.32192809 3.         4.         5.32192809]
[3.16227766 2.82842712 4.         6.32455532]


In [60]:
mat = np.random.randint(1,10,(2,3))
print(mat)


index = np.where(mat>5)
print(index)

arr = np.where(mat>5,mat,0)
print(arr)

[[9 2 8]
 [2 8 9]]
(array([0, 0, 1, 1]), array([0, 2, 1, 2]))
[[9 0 8]
 [0 8 9]]


In [65]:
z = np.random.randint(1,40,(10,))
print(z)
print(np.argmax(z))
print(np.argmin(z))
print(np.argsort(z))
#

[26  9 33 28 13 19 38  3 27 19]
6
7
[7 1 4 5 9 0 8 3 2 6]


In [73]:
##counting

a = np.random.randint(1,100,(100,))

cnt = np.count_nonzero(a<1)
print(cnt)

unique_value, count = np.unique(a, return_counts=True)
print(unique_value)
print(count)

0
[ 4  5  6  7  8 10 11 16 17 20 24 25 26 27 29 30 31 32 33 36 37 39 40 41
 43 44 46 47 48 50 55 56 57 58 59 60 61 62 63 65 67 68 69 70 71 72 73 75
 79 81 86 87 90 91 94 95 97 98]
[2 2 3 1 1 2 1 4 2 3 3 1 2 1 1 2 2 1 2 1 1 2 2 1 1 2 1 2 1 2 4 1 1 2 2 3 2
 2 1 1 1 3 1 1 1 1 2 1 1 2 5 1 2 1 2 1 2 1]


**Statistical function**

In [96]:
data = np.genfromtxt('./sample_data/student_scores.csv', delimiter=',', skip_header=1)
math_marks=data[::,:1]
print(math_marks.T)
print("min-> ",np.min(math_marks))
print("max-> ", np.max(math_marks))

print("average->>", np.mean(math_marks))

print("median->>", np.median(math_marks))

#standard deviation
std_math_marks=np.std(math_marks)
print("standard deviation->>", std_math_marks)

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
min->  45.0
max->  95.0
average->> 73.15
median->> 73.5
standard deviation->> 13.788672887555204


In [99]:
study_hours= np.array([2,4,5,7,8])
exam_scors = np.array([65,75,78,88,92])

data = np.array([study_hours,exam_scors])
print(data)
correlation = np.corrcoef(data)
print(correlation)

[[ 2  4  5  7  8]
 [65 75 78 88 92]]
[[1.         0.99859154]
 [0.99859154 1.        ]]


**Liner Algebra**

In [102]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = np.array([
    [7,8],
    [9,10],
    [11,12]
])

dot_product=np.dot(a,b)
print(dot_product)

print(np.trace(b))

[[ 58  64]
 [139 154]]
17


In [104]:
sq_mat = np.random.randint(1,10,(3,3))
det_of_sq= np.linalg.det(sq_mat)
print(det_of_sq)
#rank
rank_sq = np.linalg.matrix_rank(sq_mat)
print(rank_sq)

146.0000000000001
3
